# Generated by Django 3.0.2 on 2020-01-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hosttoremoteuser',
            options={'verbose_name': '绑定主机和用户的对应关系：HostToRemoteUser', 'verbose_name_plural': '绑定主机和用户的对应关系：HostToRemoteUser'},
        ),
        migrations.AlterField(
            model_name='romoteuser',
            name='password',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
