# Generated by Django 3.0.2 on 2020-01-12 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='host_groups',
            new_name='host_group',
        ),
    ]
