# Generated by Django 3.0.2 on 2020-01-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_auto_20200112_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='remote_users',
            field=models.ManyToManyField(to='Web.RemoteUser'),
        ),
    ]
