# Generated by Django 3.0.2 on 2020-01-20 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_host_remote_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='remote_users',
        ),
    ]
