# Generated by Django 3.0.2 on 2020-01-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0005_multitask_taskdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdetails',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'initialized'), (1, 'timeout'), (2, 'Error'), (3, 'Success')], default=0),
        ),
    ]
