# Generated by Django 3.0.2 on 2020-01-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0006_taskdetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multitask',
            name='tasktype',
            field=models.CharField(choices=[('cmd', 'CMD'), ('filetrans', 'FILES')], max_length=32),
        ),
    ]
