# Generated by Django 3.0.2 on 2020-02-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0007_auto_20200121_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='host_group',
            field=models.ManyToManyField(to='Web.HostGroup'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='host_to_remote_users',
            field=models.ManyToManyField(to='Web.HostToRemoteUser'),
        ),
    ]
